export const ORG_DISPLAY_NAME = "Your School"
export const ORG_BRANCH_NAME = "Branch Name"
export const ORG_PRODUCT_NAME = "CampusOS"
export const ORG_LOGO_PATH = "/placeholder.jpeg"
export const ORG_PRIMARY_HEX = "#5c2483"
export const SCHOOL_ID = "kidzee_mundhwa"
